### ISSUE TITLE
Question: default functions are required even if they are not being used?

### ISSUE THREAD

**Issue by soberanes** [WHMCS/sample-addon-module#6]
I have this question about the default functions inside an addon. The functions, for example: **_upgrade** , are necessary? because I have an addon but I don't use most of them. Actually I only use the _config and _output functions. 
Can I remove the other functions? or ther are an standard or something like that?
Thanks for your response.

**Comment by mattpugh** [comment]
Yes you can remove any functions you aren't using.

Only the configuration function that defines parameters and settings for a module is required.  All other functions are optional and should be omitted from your module if it does not require or utilise them.

Regards,
Matt

**Comment by soberanes** [comment]
Thanks Matt!
